Upgrade Mongoid to version 9.0.0
mongoid/mongoid-rspec pull request #245
Opened 2024-05-11 22:02 UTC by SairamSrinivasan

This PR upgrades mongoid to version 9.0.0

2024-05-11 22:06 UTC, SairamSrinivasan commented on spec/models/profile.rb
> +  embedded_in :user, inverse_of: :profile, touch: false
Embedded associations now have the touch option defaulted to `true`: https://www.mongodb.com/docs/mongoid/master/release-notes/mongoid-9.0/#embedded_in-associations-now-default-to-touch--true

2024-05-11 22:09 UTC, SairamSrinivasan commented
Ready for review.

2024-05-12 01:25 UTC, dblock requested changes
Add to CI please?

https://github.com/mongoid/mongoid-rspec/blob/master/.github/workflows/rspec.yml#L17

2024-05-12 01:35 UTC, sairamsrinivasan commented
@dblock - I appreciate the review. Please check out the latest revisions.

2024-05-12 11:53 UTC, dblock requested changes
One more nit, apologies for my OCD, looking good.

2024-05-12 11:53 UTC, dblock commented on CHANGELOG.md
> +* [#245](https://github.com/mongoid/mongoid-rspec/pull/245): Added Support for Mongoid v9.0.0 - [@saisrinivasan](https://github.com/SairamSrinivasan).
Let's match the rest of CHANGELOG: "Add support for Mongoid 9"  (Add vs. Added, lowercase support, generalize 9).

2024-05-12 15:25 UTC, sairamsrinivasan commented
> One more nit, apologies for my OCD, looking good.

No worries. Thanks for being thorough. I pushed an update.

This is unrelated but any chance that you or the other maintainers can look at my other PR: https://github.com/mongoid/mongoid-rspec/pull/246? I will likely need to rebase this.

2024-05-12 16:31 UTC, dblock commented
> This is unrelated but any chance that you or the other maintainers can look at my other PR: #246? I will likely need to rebase this.

Yes, I was doing this one first. Rebase and I'll take a look.

2024-05-12 16:31 UTC, merged