Add support to verify touch option
mongoid/mongoid-rspec pull request #246
Opened 2024-05-11 23:33 UTC by SairamSrinivasan

This PR adds support to verify touch options in rspec

2024-05-12 16:36 UTC, dblock requested changes
I think we want `with_touch` (assumes true), `with_touch(true)`, `with_touch(false)`. Add tests for each combination.

Questions:

1. Does `touch` appear in `with_options`? Add tests/examples/README.
2. Is touch always set/never set, meaning do we need to treat absence of `touch: true/false` differently?

2024-05-12 16:36 UTC, dblock commented on README.md
> +# when the touch option is provided, then we can also verify that it is set.
match other descriptions' style

"can also verify that touch is set"

2024-05-12 19:09 UTC, sairamsrinivasan commented
> I think we want `with_touch` (assumes true), `with_touch(true)`, `with_touch(false)`. Add tests for each combination.
> 
> Questions:
> 
> 1. Does `touch` appear in `with_options`? Add tests/examples/README.
> 2. Is touch always set/never set, meaning do we need to treat absence of `touch: true/false` differently?

Great suggestion. Let me incorporate the feedback.

Does `touch` appear in `with_options`? Add tests/examples/README. -> I'll check on this.


Is touch always set/never set, meaning do we need to treat absence of `touch: true/false` differently? -> 

I think it ultimately depends on the association. Based on mongoid's documentation for `embedded_in` associations, the default value for touch is `true` as of mongoid 9. Also, the touch option can take a value other than `true/false` in the form of a symbol. This symbol refers to a field defined in the parent association.

2024-05-27 22:31 UTC, sairamsrinivasan commented
@dblock - While implementing the suggested changes. I stumbled on a few things. Specifying the `touch` option on a `belongs_to` or `embedded_in` association requires the parent document's class to be loaded before the child. If this doesn't happen, the relatable module cannot resolve the parent class. There's a `NameError` that gets swallowed by library code here: https://github.com/mongodb/mongoid/blob/master/lib/mongoid/association/relatable.rb#L461

I worked around this by requiring the parent class in the child that defines the `belongs_to` or `embedded_in` association since this statement doesn't take this into account: https://github.com/mongoid/mongoid-rspec/blob/master/spec/spec_helper.rb#L20

2024-05-28 10:59 UTC, dblock requested changes
Looks nice and clean! Fix up the version change and it's good to go.

2024-05-28 10:59 UTC, dblock commented on CHANGELOG.md
> +### 4.3.0 (Next)
Undo this, we haven't released 4.2.0.

2024-05-28 10:59 UTC, dblock commented on lib/mongoid/rspec/version.rb
> +    VERSION = '4.3.0'.freeze
This should say 4.2.0.

2024-05-30 15:00 UTC, dblock approved these changes

2024-05-30 15:01 UTC, merged

2024-05-30 16:12 UTC, dblock commented
@sairamsrinivasan Any interest in helping with this gem? (see https://github.com/mongoid/mongoid-rspec/issues/237) Maybe making the next release could be a start? If yes, email me dblock at dblock dot org with your rubygems login

2024-05-30 19:06 UTC, sairamsrinivasan commented
@dblock Thanks for reviewing and merging this PR. I’d be more than happy to help with this gem. I’ll follow up through email when I get the chance.